- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print the course details
    ansible.builtin.debug:
      msg: "course name is: {{COURSE}}, Duration: {{Duration}}, Trainer: {{TRAINER}}"